# Primeros pasos con los Notebooks de IPython (parte 2)

###  Bucles

Los bucles pueden programarse de diferentes formas pero la más habitual es utilizando la sentencia `for`

In [4]:
for x in [3,5,7]:
    print(x)

3
5
7


In [5]:
for x in range(3):
    print(x)          # recordemos que range(n) recorre los números enteros de 0 a n-1

0
1
2


In [6]:
for x in range(-1,3):
    print(x)           # observa que range(a,b) recorre los números enteros de a a b-1

-1
0
1
2


A veces puede ser útil acceder a los índices de los valores de nuestra lista mientras iteramos sobre ella.

In [7]:
for i,x in enumerate(range(-2,3)):
    print(i,x)

0 -2
1 -1
2 0
3 1
4 2


También se suele utilizar la orden `while`

In [8]:
i=1
while i<= 3:
    print(i**2)
    i+=1
print('fin')

1
4
9
fin


Es interesante el uso de listas como en este ejemplo:

In [9]:
l=[x**2 for x in range(1,4)]
print(l)

[1, 4, 9]


### Funciones

En Python las funciones se definen mediante la palabra clave `def`, seguida del nombre de la funcion con sus correspondientes paréntesis y `:`. El código que sigue a continuación irá indentado y corresponderá al cuerpo de la función. 

En los paréntesis puede no aparecer ninguna variable:

In [10]:
def l3():
    for i in range (3):
        print(i**3)

In [11]:
l3()

0
1
8


O puede aparecer una variable como suele ser habitual en las funciones matemáticas:

In [12]:
def factorial(x):
    """
    Devuelve el factorial de un número x              
    
    """
    fact=1
    for i in range(2,x+1):
        fact*=i                                  ## la información comprendida entre las triples comillas
    print('El factorial de',x, 'es', fact)       ##  proporciona una documentación sobre el propósito de la función

In [13]:
factorial(5)

El factorial de 5 es 120


In [14]:
help(factorial)

Help on function factorial in module __main__:

factorial(x)
    Devuelve el factorial de un número x



En la propia definición de una función podemos dar valores por defecto a los argumentos de la función:

In [15]:
def potencia(x,n=2):
    print(x**n)

In [16]:
potencia(2)

4


In [17]:
potencia(2,3)

8


In [18]:
potencia(3,2)

9


In [19]:
potencia(x=2,n=3)

8


In [20]:
potencia(n=3,x=2)

8


Observa que si proporcionamos de manera explícita el nombre de los argumentos en la correspondiente llamada a la función, entonces ni siquiera es necesario que éstos vengan en el mismo orden en el que se definió la función.

## Librerías

Vamos a utilizar diferentes librerías de Python según el tipo de programas o funciones que vayamos a tratar. Dos de las más importantes para nosotros serán `NumPy`, `Scipy`, `SymPy` y `MatPlotlib`. Hay diferentes formas de cargar esas librerías, podéis documentaros un poco sobre este asunto. Nosotros normalmente lo haremos utilizando un pseudónimo que es lo más habitual.

In [21]:
import numpy as np              # aquí cargamos numpy con el pseudónimo np               
import sympy as sp              # y sympy  como sp
import matplotlib.pyplot as plt  # Aquí cargamos el módulo pyplot de la librería MatPlotlib 

La librería `NumPy` es una librería especializada en el cálculo numérico y el análisis de datos. `Sympy`se utiliza para el cálculo simbólico y el módulo `PyPlot` de la librería `MatPlotlib` para la representación gráfica.

Cuando utilizamos alguna función de alguna de esas librerías tendremos que escribir delante el pseudónimo como en el siguiente ejemplo:

In [22]:
x=sp.Symbol('x') # nos permite usar x de forma simbólica, como un símbolo

In [23]:
x**2

x**2

In [24]:
np.array([1,2,3])

array([1, 2, 3])

In [25]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

Hemos creado un **array** de dos formas diferentes. Los arrays de NumPy son objetos mutables igual que las listas de Python pero existen algunas diferencias entre ellos. En las listas no se pueden realizar operaciones matemáticas mientras que sí es posible en los arrays. Por otro lado, las listas permiten trabajar con diferentes tipos de datos, incluso listas anidadas.

In [26]:
l=[1,2,3]

In [27]:
2*l

[1, 2, 3, 1, 2, 3]

In [28]:
mat=np.array([[1,2,3],[4,5,6]])

In [29]:
2*mat

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
mat.shape

(2, 3)

In [31]:
mat.size

6

In [32]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.amax(mat), np.argmax(mat) # para calcular el máximo en un array y la posición que ocupa dentro del array

(6, 5)

In [34]:
np.amax(mat[0])

3

In [35]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [36]:
np.zeros([2,4]) # crea un array de ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones(3) # crea un array de unos

array([1., 1., 1.])

In [38]:
np.linspace(2,3,10) # crea un array con 10 elementos equiespaciados entre 2 y 3 (ambos incluidos)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [39]:
np.eye(4) # crea la matriz identidad de orden 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.diag([2,-3,5]) # crea una matriz diagonal introduciendo los elementos de la diagonal principal 

array([[ 2,  0,  0],
       [ 0, -3,  0],
       [ 0,  0,  5]])

In [41]:
np.random.rand(2,3) # crea un array de dos filas y tres columnas de números aleatorios entre o y 1

array([[0.80960585, 0.36084163, 0.23711127],
       [0.90676304, 0.16217566, 0.53341019]])

In [42]:
a=np.array([i**2 for i in range(3)])
a

array([0, 1, 4])

In [43]:
b=np.array([[i**2+j for j in range(3)] for i in range(2)])
b

array([[0, 1, 2],
       [1, 2, 3]])

In [44]:
n=3
b[:,:n-1]

array([[0, 1],
       [1, 2]])

In [47]:
print (b, "\n")
print (a)
np.dot(b,a) 

[[0 1 2]
 [1 2 3]] 

[0 1 4]


array([ 9, 14])

**Ejercicio:** 
- Crea un array de `Numpy` de 8 filas y 10 columnas de manera que el elemento $(i,j)$ sea  $3i+2j$ para $1\le i\le 8$ y $1\le j\le 10$. Ten en cuenta que las filas y columnas se numeran a partir de 1 pero en Python la numeración empieza en 0. El primer elemento de la matriz debe ser 5.
- Crea ahora un array $B$ de números aleatorios entre 0 y 1 de tamaño $4\times 4$. Calcula $B^{10}$.