Mario Líndez Martínez

# Práctica 1: Resolución de SEL. Métodos directos. Método de Gauss

## Ejercicio 1:

Escribe una función que resuelva por sustitución progresiva un sistema en el que la matriz de coeficientes es triangular inferior. Comprueba que se obtiene el mismo resultado utilizando dicha función que mediante la función `solve` de `NumPy` si lo aplicamos a las matrices 
$$A=\left(\begin{array}{rrr}
1 & 0 & 0 \\
2 & 2 & 0 \\
3 & 1 & 5 \end{array} \right) \qquad b=\left(2,5,1 \right) $$.

In [1]:
import numpy as np

In [2]:
"""
# Esta función resolverá un sistema Ax=b mediante sustitución progresiva
# PRE: A y b deben ser arrays de numpy
#      A debe ser una matriz triangular inferior
"""
def sust_progresiva(A, b):
    A = A.astype(float)     #Cambiamos los elementos a tipo flotante
    b = b.astype(float) 
    
    n = np.size(b)
    
    x = np.zeros(n)         #Almacenaremos aquí la solución del sistema
                       
    # Resolvemos el sistema por sustitución progresiva
    x[0] = b[0]/A[0, 0]
    
    for i in range (1, n, 1):
        x[i] = (b[i] - np.dot(A[i][:i], x[:i]))/A[i,i]
                
    return x

In [12]:
A = np.array([[1,0,0],[2,2,0],[3,1,5]])
b = np.array([2,5,1])

print (sust_progresiva(A,b))

[ 2.   0.5 -1.1]


In [13]:
print (np.linalg.solve(A, b))

[ 2.   0.5 -1.1]


## Ejercicio 2:

Modifica el código anterior para que resuelva SEL usando pivotaje parcial. Comprueba que el código funciona correctamente con las mismas matrices $A$ y $b$ del ejemplo anterior.

In [5]:
"""
# Esta función resuelve el sistema Ax=b mediante sustitución regresiva. 
# PRE: A y b deben ser arrays de numpy. 
#      A debe ser una matriz triangular superior.
"""
def sust_regresiva(A,b):
    
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    b=b.astype(float) 
    n=np.size(b)
    x=np.zeros(n)         # almacenaremos aquí la solución del sistema
                       
    # ahora se resuelve el sistema por sustitución regresiva
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):     
        x[i]=(b[i]-np.dot(A[i][i+1:],x[i+1:]))/A[i,i]
                
    return x

In [18]:
"""
# Esta función resuelve el sistema Ax=b mediante el método de Gauss. 
# PRE: A y b deben ser arrays de numpy.
"""
def GaussPvtParcial (A, b):
    A = A.astype(float)     # cambiamos los elementos a tipo flotante
    bb = (np.array([b]).transpose()).astype(float) 
    
    Ab = np.concatenate((A,bb),axis=1)  #Formamos la matriz ampliada
    n = np.size(b)
       
    # Aquí se hacen operaciones por filas en la matriz para conseguir una triangular
    for i in range(n-1):
        
        #Cálculo del pivote (pvt) parcial de la columna (por defecto se supone que ya se encuentra en la primera posicion)
        pvt = i
        for j in range (i+1, n):
            #Nuevo pivote
            if (Ab[j, i] > Ab[pvt, i]):
                pvt = j
        
        #Intercambiamos filas si es necesario
        if (pvt != i):                
            temp = Ab[pvt].copy()
            Ab[pvt] = Ab[i]
            Ab[i] = temp

        #Generamos ceros en la columna
        for j in range(i+1, n):
            m = Ab[j,i]/Ab[i,i]
            Ab[j] = Ab[j] - (m * Ab[i])
        
    # ahora se resuelve el sistema por sustitución regresiva
    AG=Ab[:,:n]
    bG=Ab[:,n].transpose()
    x=sust_regresiva(AG,bG)
                
    return x

In [19]:
A = np.array([[2,4,1],[1,3,5],[-1,0,1]])
b = np.array([2,-5,1])

print (GaussPvtParcial(A,b))

[-2.86666667  2.4        -1.86666667]


In [10]:
print(np.linalg.solve(A, b))

[-2.86666667  2.4        -1.86666667]
