#### Hecho por: Mario Líndez Martínez

### Contenidos

* [Práctica 0](#Pract-0)
    * [Ejercicio_0.1](#Ej-0.1)
    * [Ejercicio_0.2](#Ej-0.2)
        
* [Práctica_1](#Pract-1)
    * [Ejercicio_1.1](#Ej-1.1)
    * [Ejercicio_1.2](#Ej-1.2)
        
* [Práctica_2](#Pract-2)
    * [Ejercicio_2.1](#Ej-2.1)
    * [Ejercicio_2.2](#Ej-2.2)
        
* [Práctica_3](#Pract-3)
    * [Ejercicio_3.1](#Ej-3.1)
    * [Ejercicio_3.2](#Ej-3.2)
    
* [Ejercicio Final](#Ej-Final)

---

<h1>Práctica 0 <a class="anchor" id="Pract-0">

<h4>Ejercicio 1: <a class="anchor" id="Ej-0.1">

- Escribe un pequeño programa que calcule el máximo entre 4 números que debe introducir el usuario.

In [2]:
print ("Introduce 4 números: \n")

#Lectura anticipada del primer valor, lo usaremos como primer valor maximo introducido
num = float (input ("- Num 1: "))
maximo = num

for i in range(2, 5):
    num = float (input ("- Num %d: " %i))
    
    #Nuevo maximo
    if (maximo < num):
        maximo = num

print ("\nEl máximo valor introducido es el: ", maximo)

Introduce 4 números: 

- Num 1: 5
- Num 2: 87
- Num 3: 2
- Num 4: 1

El máximo valor introducido es el:  87.0


<h4>Ejercicio 2: <a class="anchor" id="Ej-0.2">

- Crea un array de `Numpy` de 8 filas y 10 columnas de manera que el elemento $(i,j)$ sea  $3i+2j$ para $1\le i\le 8$ y $1\le j\le 10$. Ten en cuenta que las filas y columnas se numeran a partir de 1 pero en Python la numeración empieza en 0. El primer elemento de la matriz debe ser 5.

In [3]:
import numpy as np              # aquí cargamos numpy con el pseudónimo np               
import sympy as sp              # y sympy  como sp

In [4]:
mat = np.array([[((3*i)+(2*j)) for j in range(1,11)] for i in range(1,9)])
print (mat)

[[ 5  7  9 11 13 15 17 19 21 23]
 [ 8 10 12 14 16 18 20 22 24 26]
 [11 13 15 17 19 21 23 25 27 29]
 [14 16 18 20 22 24 26 28 30 32]
 [17 19 21 23 25 27 29 31 33 35]
 [20 22 24 26 28 30 32 34 36 38]
 [23 25 27 29 31 33 35 37 39 41]
 [26 28 30 32 34 36 38 40 42 44]]


- Crea ahora un array $B$ de números aleatorios entre 0 y 1 de tamaño $4\times 4$. Calcula $B^{10}$.

In [5]:
#Creamos el array de números aleatorios
b = np.random.rand(4,4)
print (b)

[[0.65906946 0.56450495 0.05000127 0.31837377]
 [0.40306132 0.92986636 0.62907554 0.86767932]
 [0.71840582 0.46730239 0.85508803 0.01568134]
 [0.58758561 0.77295433 0.5633022  0.08419974]]


In [6]:
#Potencia de 10 de la matriz
a = np.linalg.matrix_power(b, 10)
print (a)

[[ 452.93950894  543.79987521  404.63362665  298.16947298]
 [ 834.80012536 1002.26291408  745.77051186  549.54790478]
 [ 550.45882422  660.88111343  491.75335743  362.36561989]
 [ 585.17224313  702.55878999  522.76462735  385.2180086 ]]


---

<h1>Práctica 1 <a class="anchor" id="Pract-1">

<h4>Ejercicio 1: <a class="anchor" id="Ej-1.1">

- Escribe una función que resuelva por sustitución progresiva un sistema en el que la matriz de coeficientes es triangular inferior. Comprueba que se obtiene el mismo resultado utilizando dicha función que mediante la función `solve` de `NumPy` si lo aplicamos a las matrices 
$$A=\left(\begin{array}{rrr}
1 & 0 & 0 \\
2 & 2 & 0 \\
3 & 1 & 5 \end{array} \right) \qquad b=\left(2,5,1 \right) $$.

In [7]:
import numpy as np

In [8]:
"""
# Esta función resolverá un sistema Ax=b mediante sustitución progresiva
# PRE: A y b deben ser arrays de numpy
#      A debe ser una matriz triangular inferior
"""
def sust_progresiva(A, b):
    A = A.astype(float)     #Cambiamos los elementos a tipo flotante
    b = b.astype(float) 
    
    n = np.size(b)
    
    x = np.zeros(n)         #Almacenaremos aquí la solución del sistema
                       
    # Resolvemos el sistema por sustitución progresiva
    x[0] = b[0]/A[0, 0]
    
    for i in range (1, n, 1):
        x[i] = (b[i] - np.dot(A[i][:i], x[:i]))/A[i,i]
                
    return x

In [9]:
"""   MAIN   """
A = np.array([[1,0,0],[2,2,0],[3,1,5]])
b = np.array([2,5,1])

print (sust_progresiva(A,b))

[ 2.   0.5 -1.1]


In [10]:
#Comprobamos que nuestra función funciona correctamente
print (np.linalg.solve(A, b))

[ 2.   0.5 -1.1]


<h4>Ejercicio 2: <a class="anchor" id="Ej-1.2">

Modifica el código anterior para que resuelva SEL usando pivotaje parcial. Comprueba que el código funciona correctamente con las mismas matrices $A$ y $b$ del ejemplo anterior.

In [11]:
"""
# Esta función resuelve el sistema Ax=b mediante sustitución regresiva. 
# PRE: A y b deben ser arrays de numpy. 
#      A debe ser una matriz triangular superior.
"""
def sust_regresiva(A,b):
    
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    b=b.astype(float) 
    n=np.size(b)
    x=np.zeros(n)         # almacenaremos aquí la solución del sistema
                       
    # ahora se resuelve el sistema por sustitución regresiva
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):     
        x[i]=(b[i]-np.dot(A[i][i+1:],x[i+1:]))/A[i,i]
                
    return x

In [12]:
"""
# Esta función resuelve el sistema Ax=b mediante el método de Gauss. 
# PRE: A y b deben ser arrays de numpy.
"""
def GaussPvtParcial (A, b):
    A = A.astype(float)     # cambiamos los elementos a tipo flotante
    bb = (np.array([b]).transpose()).astype(float) 
    
    Ab = np.concatenate((A,bb),axis=1)  #Formamos la matriz ampliada
    n = np.size(b)
       
    # Aquí se hacen operaciones por filas en la matriz para conseguir una triangular
    for i in range(n-1):
        
        #Cálculo del pivote (pvt) parcial de la columna (por defecto se supone que ya se encuentra en la primera posicion)
        pvt = i
        for j in range (i+1, n):
            #Nuevo pivote
            if (Ab[j, i] > Ab[pvt, i]):
                pvt = j
        
        #Intercambiamos filas si es necesario
        if (pvt != i):                
            temp = Ab[pvt].copy()
            Ab[pvt] = Ab[i]
            Ab[i] = temp

        #Generamos ceros en la columna
        for j in range(i+1, n):
            m = Ab[j,i]/Ab[i,i]
            Ab[j] = Ab[j] - (m * Ab[i])
        
    # ahora se resuelve el sistema por sustitución regresiva
    AG=Ab[:,:n]
    bG=Ab[:,n].transpose()
    x=sust_regresiva(AG,bG)
                
    return x

In [13]:
"""   MAIN   """
A = np.array([[2,4,1],[1,3,5],[-1,0,1]])
b = np.array([2,-5,1])

print (GaussPvtParcial(A,b))

[-2.86666667  2.4        -1.86666667]


In [14]:
#Comprobamos que nuestra función funciona correctamente
print(np.linalg.solve(A, b))

[-2.86666667  2.4        -1.86666667]


---

<h1>Práctica 2 <a class="anchor" id="Pract-2">

<h4>Ejercicio 1: <a class="anchor" id="Ej-2.1">

- Utilizando la descomposición LU de esta práctica y las sustituciones progresiva y regresiva de la práctica anterior, resuelve el sistema $A x=b$ donde
$$A=\left(\begin{array}{rrr}
1 & 4 & 1 \\
1 & 3 & 5 \\
-2 & 0 & 1 \end{array} \right) \qquad b=\left(2,-5,1 \right) $$ 

In [ ]:
import numpy as np
from scipy.linalg import lu, lu_solve, lu_factor

In [ ]:
"""
# Esta función resolverá un sistema Ax=b mediante sustitución progresiva
# PRE: A y b deben ser arrays de numpy
#      A debe ser una matriz triangular inferior
"""
def sust_progresiva(A, b):
    A = A.astype(float)     #Cambiamos los elementos a tipo flotante
    b = b.astype(float) 
    
    n = np.size(b)
    
    x = np.zeros(n)         #Almacenaremos aquí la solución del sistema
                       
    # Resolvemos el sistema por sustitución progresiva
    x[0] = b[0]/A[0, 0]
    
    for i in range (1, n, 1):
        x[i] = (b[i] - np.dot(A[i][:i], x[:i]))/A[i,i]
                
    return x

In [ ]:
"""
Esta función resuelve el sistema Ax=b mediante sustitución regresiva. 
PRE: A y b deben ser arrays de numpy. 
     A debe ser una matriz triangular superior.
"""
def sust_regresiva(A,b):
    
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    b=b.astype(float) 
    n=np.size(b)
    x=np.zeros(n)         # almacenaremos aquí la solución del sistema
                       
    # ahora se resuelve el sistema por sustitución regresiva
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):     
        x[i]=(b[i]-np.dot(A[i][i+1:],x[i+1:]))/A[i,i]
                
    return x

In [ ]:
"""
Esta función calcula la descomposición LU de Doolittle de una matriz A sin intercambio de filas.
A debe ser un array de Numpy.
"""
def LU_desc(A):
    n=np.shape(A)[1]
    U=np.zeros([n,n])
    L=np.eye(n)
    
    for k in range(n-1):
        U[k,k]=A[k,k]-np.dot(L[k,:k],U[:k,k])
        for j in range(k+1,n):
            U[k,j]=A[k,j]-np.dot(L[k,:k],U[:k,j])
        for j in range(k+1):
            L[k+1,j]=(A[k+1,j]-np.dot(L[k+1,:j],U[:j,j]))/U[j,j]
    U[n-1,n-1]=A[n-1,n-1]-np.dot(L[n-1,:n-1],U[:n-1,n-1])
    return L, U

In [ ]:
"""
Esta función resuelve un sistema de ecuaciones Ax = b usando la descomposición LU de Doolitle sin intercambio de filas
PRE: A y b deben ser arrays de numpy
"""
def ResolverPorLUDoolitle(A, b):
    L, U = LU_desc(A)
    
    y = sust_progresiva(L, b)
    
    x = sust_regresiva(U, y)
    
    return (x)

In [ ]:
"""   MAIN   """
A = np.array([[1, 4, 1], [1, 3, 5], [-2, 0, 1]])
b = np.array([2, -5, 1])

x = ResolverPorLUDoolitle(A, b)
print (x)


In [ ]:
#Comprobamos que nuestra función funciona correctamente
print (lu_solve(lu_factor(A),b))

<h4>Ejercicio 2: <a class="anchor" id="Ej-2.2">

- Define una función que resuelva un sistema de ecuaciones lineales mediante la factorización de Cholesky. Comprueba su funcionamiento para intentar resolver el sistema $A x=b$ donde $b=\left(2,-5,1 \right)$ en los casos de los ejemplos anteriores:
$$A=\left(\begin{array}{rrr}
2 & 4 & 1 \\
4 & 10 & 1 \\
1 & 1 & 5 \end{array} \right) \qquad 
A=\left(\begin{array}{rrr}
2 & 4 & 1 \\
4 & 0 & 1 \\
1 & 1 & 5 \end{array} \right)$$ 

**No** se permite utilizar la función `linalg.cholesky`de `NumPy`

In [ ]:
"""
Esta función descompone una matriz simétrica usando la factorización de Cholesky
Devolverá solo el valor de L
"""
def Cholesky(A):
    n = np.shape(A)[1]
    L = np.zeros([n,n])
    
    for i in range (0, n):
        L[i,i] = np.sqrt(A[i,i] - np.dot(L[i, :i], L[i, :i]))
        
        for j in range (i+1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], L[i, :i]))/L[i,i]
    
    
    return (L)

In [ ]:
"""
Esta función resolverá un sistema de ecuaciones usando la factorización de Cholesky

"""
def ResolverPorCholesky(A,b):
    L = Cholesky(A)
    Lt = np.transpose(L)
    
    # Ax = b --> LUx = b --> L(Ux) = b
    # Ux = y ; Ly = b")
    # Donde U = l transpuesta
    
    y = sust_progresiva(L,b)
    
    x = sust_regresiva(Lt,y)
    
    return (x)

In [ ]:
"""
MAIN
"""
print ("Caso 1:")
A = np.array([[2, 4, 1], [4, 10, 1], [1, 1, 5]])
b = np.array([2, -5, 1])

x = ResolverPorCholesky(A,b)
print ("x = \n", x)

print ("\nCaso 2:")
A = np.array([[2, 4, 1], [4, 0, 1], [1, 1, 5]])

x = ResolverPorCholesky(A,b)

print ("x = \n", x)

---

<h1>Práctica 3 <a class="anchor" id="Pract-3">

<h4>Ejercicio 1 <a class="anchor" id="Ej-3.1">

Modifica el código anterior para resolver de forma aproximada un sistema de ecuaciones lineales utilizando el método de **Gauss-Seidel**. Comprueba el funcionamiento del programa con el sistema $A x=b$ donde
$$A=\left(\begin{array}{rrr}
10 & 4 & 1 \\
4 & 10 & 1 \\
1 & 1 & 5 \end{array} \right) \qquad b=\left(15,15,7 \right) $$ 

In [1]:
import numpy as np

In [2]:
"""
Esta función resuelve el sistema Ax=b de forma aproximada mediante el método iterativo de Gauss-Seidel 
empezando las iteraciones en el vector nulo.
PRE: Las matrices A y b deben ser arrays de NumPy.
     El número máximo de iteraciones se puede introducir por el usuario y es 1000 por defecto.
     La tolerancia también se puede introducir por el usuario y es 10^(-10) por defecto.
     El método se interrumpe cuando se alcanza el número máximo de iteraciones o cuando la tolerancia es 
     menor que la indicada.
    
"""
def GaussSeidel(A, b, maxiter=1000, tol=10**(-10)):
    n = np.shape(A)[1] # se calcula la dimensión de A
    d = np.diag(A)     # obtenemos un array con los elementos de la diagonal de la matriz A
    D = np.diag(d)     # creamos un array diagonal con los elementos de d
    R = A-D            # matriz con los elementos que no están en la diagonal
    x = np.zeros(n)
    y = np.zeros(n)
    
    if np.prod(d)==0:
        print('Hay elementos nulos en la diagonal de la matriz')
    else:
        k = 1
        er = 1
        nx = 1
        while (er > tol*nx and k < maxiter):
            nx = np.linalg.norm(x, 1)
            for i in range(n):
                y[i] = (b[i] - np.dot(A[i, :i], y[:i]) - np.dot(A[i, (i+1):], x[(i+1):])) / A[i, i]
            er = np.linalg.norm(y-x,1) # calculamos la norma de la diferencia entre y y el resultado de la iteración anterior        
            x = np.copy(y)
            #print('Iteración k=', k, '  x^(k)= ', x ) # descomentar si se quieren ver las iteraciones.
            k += 1
        return x

In [3]:
A = np.array([[10, 4, 1], [4, 10, 1], [1, 1, 5]])
b = np.array([15, 15, 7])

x = GaussSeidel(A, b)

print (x)

[1. 1. 1.]


<h4> Ejercicio 2 <a class="anchor" id="Ej-3.2">

Una vez programado Gauss-Seidel, haz las modificaciones oportunas para definir una función que resuelva un sistema utilizando un método de relajación con la constante $\omega$ introducida por el usuario.

In [4]:
"""
Esta función resuelve el sistema Ax=b de forma aproximada mediante el método iterativo de Gauss-Seidel 
empezando las iteraciones en el vector nulo.
PRE: - Las matrices A y b deben ser arrays de NumPy.
     - El número máximo de iteraciones se puede introducir por el usuario y es 1000 por defecto.
     - La tolerancia también se puede introducir por el usuario y es 10^(-10) por defecto.
     - El método se interrumpe cuando se alcanza el número máximo de iteraciones o cuando la tolerancia es 
       menor que la indicada.
     - El valor de la constante w debe ser 0 < w < 2 para que el método funcione
    
"""
def Relajacion(A, b, w, maxiter=1000, tol=10**(-10)):
    n = np.shape(A)[1] # se calcula la dimensión de A
    d = np.diag(A)     # obtenemos un array con los elementos de la diagonal de la matriz A
    D = np.diag(d)     # creamos un array diagonal con los elementos de d
    R = A-D            # matriz con los elementos que no están en la diagonal
    x = np.zeros(n)
    y = np.zeros(n)
    
    if ((0 < w) and (w < 2)):
        if np.prod(d)==0:
            print('Hay elementos nulos en la diagonal de la matriz')
        else:
            k = 1
            er = 1
            nx = 1
            while (er > tol*nx and k < maxiter):
                nx = np.linalg.norm(x, 1)
                for i in range(n):
                    y[i] = ((w * (b[i] - np.dot(A[i, :i], y[:i]) - np.dot(A[i, (i+1):], x[(i+1):]))) / A[i, i]) + ((1 - w)*x[i])
                er = np.linalg.norm(y-x,1)  # calculamos la norma de la diferencia entre y y el resultado de la iteración anterior        
                x = np.copy(y)
                #print('Iteración k=', k, '  x^(k)= ', x ) # descomentar si se quieren ver las iteraciones.
                k += 1
        
    else:
        print ("Error: El método de relajación solo puede ser convergente si 0 < w < 2")
    return x
    

In [5]:
A = np.array([[10, 4, 1], [4, 10, 1], [1, 1, 5]])
b = np.array([15, 15, 7])

x = Relajacion(A, b, 1.5)

print (x)

[1. 1. 1.]


--- 

<h1> Ejercicio final <a class="anchor" id="Ej-Final">

Define una matriz A cuadrada de orden 20 cuyo elemento $a_{ij}=1/(i+j)$ siempre que $i\ne j$ y $a_{ii}=20 *i^2$. Define también un vector b cuyas componentes sean todas iguales a 20. Resuelve ahora el sistema $A x=b$ con **todos los métodos** que hemos visto. Comenta los resultados.

In [ ]:
#========================= Sustituciones =========================

In [ ]:
"""
# Esta función resolverá un sistema Ax=b mediante sustitución progresiva
# PRE: A y b deben ser arrays de numpy
#      A debe ser una matriz triangular inferior
"""
def sust_progresiva(A, b):
    A = A.astype(float)     #Cambiamos los elementos a tipo flotante
    b = b.astype(float) 
    
    n = np.size(b)
    
    x = np.zeros(n)         #Almacenaremos aquí la solución del sistema
                       
    # Resolvemos el sistema por sustitución progresiva
    x[0] = b[0]/A[0, 0]
    
    for i in range (1, n, 1):
        x[i] = (b[i] - np.dot(A[i][:i], x[:i]))/A[i,i]
                
    return x

"""
# Esta función resuelve el sistema Ax=b mediante sustitución regresiva. 
# PRE: A y b deben ser arrays de numpy. 
#      A debe ser una matriz triangular superior.
"""
def sust_regresiva(A,b):
    
    A=A.astype(float)     # cambiamos los elementos a tipo flotante
    b=b.astype(float) 
    n=np.size(b)
    x=np.zeros(n)         # almacenaremos aquí la solución del sistema
                       
    # ahora se resuelve el sistema por sustitución regresiva
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):     
        x[i]=(b[i]-np.dot(A[i][i+1:],x[i+1:]))/A[i,i]
                
    return x

In [ ]:
#========================= Métodos de Gauss (Pivotaje Parcial) =========================

In [ ]:
"""
# Esta función resuelve el sistema Ax=b mediante el método de Gauss. 
# PRE: A y b deben ser arrays de numpy.
"""
def GaussPvtParcial (A, b):
    A = A.astype(float)     # cambiamos los elementos a tipo flotante
    bb = (np.array([b]).transpose()).astype(float) 
    
    Ab = np.concatenate((A,bb),axis=1)  #Formamos la matriz ampliada
    n = np.size(b)
       
    # Aquí se hacen operaciones por filas en la matriz para conseguir una triangular
    for i in range(n-1):
        
        #Cálculo del pivote (pvt) parcial de la columna (por defecto se supone que ya se encuentra en la primera posicion)
        pvt = i
        for j in range (i+1, n):
            #Nuevo pivote
            if (Ab[j, i] > Ab[pvt, i]):
                pvt = j
        
        #Intercambiamos filas si es necesario
        if (pvt != i):                
            temp = Ab[pvt].copy()
            Ab[pvt] = Ab[i]
            Ab[i] = temp

        #Generamos ceros en la columna
        for j in range(i+1, n):
            m = Ab[j,i]/Ab[i,i]
            Ab[j] = Ab[j] - (m * Ab[i])
        
    # ahora se resuelve el sistema por sustitución regresiva
    AG=Ab[:,:n]
    bG=Ab[:,n].transpose()
    x=sust_regresiva(AG,bG)
                
    return x

In [ ]:
#========================= Métodos de descomposición =========================

In [ ]:
# ----- Descomposición de Doolitle

In [ ]:
"""
Esta función calcula la descomposición LU de Doolittle de una matriz A sin intercambio de filas.
A debe ser un array de Numpy.
"""
def LU_desc(A):
    n=np.shape(A)[1]
    U=np.zeros([n,n])
    L=np.eye(n)
    
    for k in range(n-1):
        U[k,k]=A[k,k]-np.dot(L[k,:k],U[:k,k])
        for j in range(k+1,n):
            U[k,j]=A[k,j]-np.dot(L[k,:k],U[:k,j])
        for j in range(k+1):
            L[k+1,j]=(A[k+1,j]-np.dot(L[k+1,:j],U[:j,j]))/U[j,j]
    U[n-1,n-1]=A[n-1,n-1]-np.dot(L[n-1,:n-1],U[:n-1,n-1])
    return L, U

In [ ]:
"""
Esta función resuelve un sistema de ecuaciones Ax = b usando la descomposición LU de Doolitle sin intercambio de filas
PRE: A y b deben ser arrays de numpy
"""
def ResolverPorLUDoolitle(A, b):
    L, U = LU_desc(A)
    
    y = sust_progresiva(L, b)
    
    x = sust_regresiva(U, y)
    
    return (x)

In [ ]:
# ----- Descomposición de Cholesky

In [ ]:
"""
Esta función descompone una matriz simétrica usando la factorización de Cholesky
Devolverá solo el valor de L
PRE: La matriz A debe ser un array de numpy
"""
def Cholesky(A):
    n = np.shape(A)[1]
    L = np.zeros([n,n])
    
    for i in range (0, n):
        L[i,i] = np.sqrt(A[i,i] - np.dot(L[i, :i], L[i, :i]))
        
        for j in range (i+1, n):
            L[j, i] = (A[j, i] - np.dot(L[j, :i], L[i, :i]))/L[i,i]
    
    
    return (L)

In [ ]:
"""
Esta función resolverá un sistema de ecuaciones Ax=b usando la factorización de Cholesky
PRE: A y b deben ser arrays de numpy
"""
def ResolverPorCholesky(A,b):
    L = Cholesky(A)
    Lt = np.transpose(L)
    
    # Ax = b --> LUx = b --> L(Ux) = b
    # Ux = y ; Ly = b")
    # Donde U = l transpuesta
    
    y = sust_progresiva(L,b)
    
    x = sust_regresiva(Lt,y)
    
    return (x)

In [ ]:
#========================= Métodos iterativos =========================

In [ ]:
"""
Esta función resuelve el sistema Ax=b de forma aproximada mediante el método iterativo de Jacobi empezando las iteraciones
en el vector nulo.
Las matrices A y b deben ser arrays de NumPy.
El número máximo de iteraciones se puede introducir por el usuario y es 1000 por defecto.
La tolerancia también se puede introducir por el usuario y es 10^(-10) por defecto.
El método se interrumpe cuando se alcanza el número máximo de iteraciones o cuando la tolerancia es menor que la indicada.

"""
def Jacobi2(A, b, maxiter=1000, tol=10**(-10)):    
    n=np.shape(A)[1] # se calcula la dimensión de A
    d=np.diag(A)     # obtenemos un array con los elementos de la diagonal de la matriz A
    D=np.diag(d)     # creamos un array diagonal con los elementos de d
    R=A-D            # matriz con los elementos que no están en la diagonal
    x=np.zeros(n)
    y=np.zeros(n)
          
    if np.prod(d)==0:
        print('Hay elementos nulos en la diagonal de la matriz')
    else:
        k=1
        er=1
        nx=1
        while (er>tol*nx and k<maxiter):
            nx=np.linalg.norm(x,1)        
            for i in range(n):
                y[i] = (b[i] - np.dot(A[i,:i],x[:i]) - np.dot(A[i,i+1:],x[i+1:]) )/A[i,i]  
            er=np.linalg.norm(y-x,1)   # calculamos la norma de la diferencia entre y y el resultado de la iteración anterior        
            x=np.copy(y)
           # print('Iteración k=', k, '  x^(k)= ', x ) # descomentar si se quieren ver las iteraciones.
            k+=1
        return x

In [ ]:
"""
Esta función resuelve el sistema Ax=b de forma aproximada mediante el método iterativo de Gauss-Seidel 
empezando las iteraciones en el vector nulo.
PRE: Las matrices A y b deben ser arrays de NumPy.
     El número máximo de iteraciones se puede introducir por el usuario y es 1000 por defecto.
     La tolerancia también se puede introducir por el usuario y es 10^(-10) por defecto.
     El método se interrumpe cuando se alcanza el número máximo de iteraciones o cuando la tolerancia es 
     menor que la indicada.
    
"""
def GaussSeidel(A, b, maxiter=1000, tol=10**(-10)):
    n = np.shape(A)[1] # se calcula la dimensión de A
    d = np.diag(A)     # obtenemos un array con los elementos de la diagonal de la matriz A
    D = np.diag(d)     # creamos un array diagonal con los elementos de d
    R = A-D            # matriz con los elementos que no están en la diagonal
    x = np.zeros(n)
    y = np.zeros(n)
    
    if np.prod(d)==0:
        print('Hay elementos nulos en la diagonal de la matriz')
    else:
        k = 1
        er = 1
        nx = 1
        while (er > tol*nx and k < maxiter):
            nx = np.linalg.norm(x, 1)
            for i in range(n):
                y[i] = (b[i] - np.dot(A[i, :i], y[:i]) - np.dot(A[i, (i+1):], x[(i+1):])) / A[i, i]
            er = np.linalg.norm(y-x,1) # calculamos la norma de la diferencia entre y y el resultado de la iteración anterior        
            x = np.copy(y)
            #print('Iteración k=', k, '  x^(k)= ', x ) # descomentar si se quieren ver las iteraciones.
            k += 1
        return x

In [ ]:
"""
Esta función resuelve el sistema Ax=b de forma aproximada mediante el método iterativo de Gauss-Seidel 
empezando las iteraciones en el vector nulo.
PRE: - Las matrices A y b deben ser arrays de NumPy.
     - El número máximo de iteraciones se puede introducir por el usuario y es 1000 por defecto.
     - La tolerancia también se puede introducir por el usuario y es 10^(-10) por defecto.
     - El método se interrumpe cuando se alcanza el número máximo de iteraciones o cuando la tolerancia es 
       menor que la indicada.
     - El valor de la constante w debe ser 0 < w < 2 para que el método funcione
    
"""
def Relajacion(A, b, w, maxiter=1000, tol=10**(-10)):
    n = np.shape(A)[1] # se calcula la dimensión de A
    d = np.diag(A)     # obtenemos un array con los elementos de la diagonal de la matriz A
    D = np.diag(d)     # creamos un array diagonal con los elementos de d
    R = A-D            # matriz con los elementos que no están en la diagonal
    x = np.zeros(n)
    y = np.zeros(n)
    
    if ((0 < w) and (w < 2)):
        if np.prod(d)==0:
            print('Hay elementos nulos en la diagonal de la matriz')
        else:
            k = 1
            er = 1
            nx = 1
            while (er > tol*nx and k < maxiter):
                nx = np.linalg.norm(x, 1)
                for i in range(n):
                    y[i] = ((w * (b[i] - np.dot(A[i, :i], y[:i]) - np.dot(A[i, (i+1):], x[(i+1):]))) / A[i, i]) + ((1 - w)*x[i])
                er = np.linalg.norm(y-x,1)  # calculamos la norma de la diferencia entre y y el resultado de la iteración anterior        
                x = np.copy(y)
                #print('Iteración k=', k, '  x^(k)= ', x ) # descomentar si se quieren ver las iteraciones.
                k += 1
        
    else:
        print ("Error: El método de relajación solo puede ser convergente si 0 < w < 2")
    return x
    

In [ ]:
"""   MAIN   """

#Creamos la matriz cuadrada de orden 20 con todo ceros, luego asignaremos el valor de cada elemento
A = np.zeros([20, 20])
for i in range (1, 21):
    for j in range (1, 21):
        if (i == j):
            A[i-1, j-1] = 20*(i*i)
        else:
            A[i-1, j-1] = 1/(i + j)

#Creamos el vector b en la que todas sus componentes son iguales a 20
b = np.full(20, 20)

#Resolvemos por Gauss usando pivotaje parcial
x = GaussPvtParcial(A, b)
print ("Solución por Gauss:\nx = ", x, "\n")

In [ ]:
#Resolvemos por descomposición L,U usando la descomposición de Doolitle
x = ResolverPorLUDoolitle(A,b)
print ("Solución por Doolitle:\nx = ", x, "\n")

In [ ]:
#Resolvemos por descomposición L,U usando la descomposición de Cholesky
x = ResolverPorCholesky(A, b)
print ("Solución por Cholesky:\nx = ", x, "\n")

In [ ]:
#Resolvemos por el método de Jacobi
x = Jacobi2(A, b)
print ("Solución por Jacobi:\nx = ", x, "\n")

In [ ]:
#Resolvemos por el método de Gauss-Seidel
x = GaussSeidel(A, b)
print ("Solución por Gauss-Seidel:\nx = ", x, "\n")

In [ ]:
#Resolvemos por el método de Relajación
w = 1.5
x = Relajacion(A, b, w)
print ("Solución por Relajación:\nx = ", x, "\n")

In [ ]:
np.linalg.solve(A,b)